name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: Muhammadali922
          outputs: assets/github-snake-dark.svg
          palette: github-dark   # qora fon

      - name: Commit snake to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/github-snake-dark.svg
          git commit -m "update dark snake animation" || echo "No changes"
          git push
